// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    ErrorMessage,
    LoginRequest,
    SignupRequest,
} from '../models';

export interface AuthenticateUserRequest {
    loginRequest: LoginRequest;
}

export interface RegisterUserRequest {
    signupRequest: SignupRequest;
}

/**
 * no description
 */
export class AuthControllerApi extends BaseAPI {

    /**
     */
    authenticateUser({ loginRequest }: AuthenticateUserRequest): Observable<object>
    authenticateUser({ loginRequest }: AuthenticateUserRequest, opts?: OperationOpts): Observable<AjaxResponse<object>>
    authenticateUser({ loginRequest }: AuthenticateUserRequest, opts?: OperationOpts): Observable<object | AjaxResponse<object>> {
        throwIfNullOrUndefined(loginRequest, 'loginRequest', 'authenticateUser');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<object>({
            url: '/api/auth/signin',
            method: 'POST',
            headers,
            body: loginRequest,
        }, opts?.responseOpts);
    };

    /**
     */
    logoutUser(): Observable<object>
    logoutUser(opts?: OperationOpts): Observable<AjaxResponse<object>>
    logoutUser(opts?: OperationOpts): Observable<object | AjaxResponse<object>> {
        return this.request<object>({
            url: '/api/auth/signout',
            method: 'POST',
        }, opts?.responseOpts);
    };

    /**
     */
    refreshToken(): Observable<object>
    refreshToken(opts?: OperationOpts): Observable<AjaxResponse<object>>
    refreshToken(opts?: OperationOpts): Observable<object | AjaxResponse<object>> {
        return this.request<object>({
            url: '/api/auth/refreshtoken',
            method: 'POST',
        }, opts?.responseOpts);
    };

    /**
     */
    registerUser({ signupRequest }: RegisterUserRequest): Observable<object>
    registerUser({ signupRequest }: RegisterUserRequest, opts?: OperationOpts): Observable<AjaxResponse<object>>
    registerUser({ signupRequest }: RegisterUserRequest, opts?: OperationOpts): Observable<object | AjaxResponse<object>> {
        throwIfNullOrUndefined(signupRequest, 'signupRequest', 'registerUser');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<object>({
            url: '/api/auth/signup',
            method: 'POST',
            headers,
            body: signupRequest,
        }, opts?.responseOpts);
    };

}
