// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type {
    ErrorMessage,
} from '../models';

export interface GetFileRequest {
    filename: string;
}

/**
 * no description
 */
export class FilesControllerApi extends BaseAPI {

    /**
     */
    getFile({ filename }: GetFileRequest): Observable<Blob>
    getFile({ filename }: GetFileRequest, opts?: OperationOpts): Observable<AjaxResponse<Blob>>
    getFile({ filename }: GetFileRequest, opts?: OperationOpts): Observable<Blob | AjaxResponse<Blob>> {
        throwIfNullOrUndefined(filename, 'filename', 'getFile');

        return this.request<Blob>({
            url: '/api/files/{filename}'.replace('{filename}', encodeURI(filename)),
            method: 'GET',
            responseType: 'blob',
        }, opts?.responseOpts);
    };

}
