// tslint:disable
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    ErrorMessage,
} from '../models';

/**
 * no description
 */
export class TestControllerApi extends BaseAPI {

    /**
     */
    adminAccess(): Observable<string>
    adminAccess(opts?: OperationOpts): Observable<AjaxResponse<string>>
    adminAccess(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<string>({
            url: '/api/test/admin',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    allAccess(): Observable<string>
    allAccess(opts?: OperationOpts): Observable<AjaxResponse<string>>
    allAccess(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<string>({
            url: '/api/test/all',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    moderatorAccess(): Observable<string>
    moderatorAccess(opts?: OperationOpts): Observable<AjaxResponse<string>>
    moderatorAccess(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<string>({
            url: '/api/test/mod',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    userAccess(): Observable<string>
    userAccess(opts?: OperationOpts): Observable<AjaxResponse<string>>
    userAccess(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<string>({
            url: '/api/test/user',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
