// tslint:disable
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    ErrorMessage,
    User,
} from '../models';

export interface CreateUserRequest {
    user: User;
}

export interface DeleteTutorialRequest {
    id: number;
}

export interface GetAllUserRequest {
    username?: string;
}

export interface GetUserByIdRequest {
    id: number;
}

export interface UpdateUserRequest {
    id: number;
    user: User;
}

/**
 * no description
 */
export class UserControllerApi extends BaseAPI {

    /**
     */
    createUser({ user }: CreateUserRequest): Observable<User>
    createUser({ user }: CreateUserRequest, opts?: OperationOpts): Observable<AjaxResponse<User>>
    createUser({ user }: CreateUserRequest, opts?: OperationOpts): Observable<User | AjaxResponse<User>> {
        throwIfNullOrUndefined(user, 'user', 'createUser');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<User>({
            url: '/api/users',
            method: 'POST',
            headers,
            body: user,
        }, opts?.responseOpts);
    };

    /**
     */
    deleteAllUsers(): Observable<string>
    deleteAllUsers(opts?: OperationOpts): Observable<AjaxResponse<string>>
    deleteAllUsers(opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<string>({
            url: '/api/users',
            method: 'DELETE',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    deleteTutorial({ id }: DeleteTutorialRequest): Observable<string>
    deleteTutorial({ id }: DeleteTutorialRequest, opts?: OperationOpts): Observable<AjaxResponse<string>>
    deleteTutorial({ id }: DeleteTutorialRequest, opts?: OperationOpts): Observable<string | AjaxResponse<string>> {
        throwIfNullOrUndefined(id, 'id', 'deleteTutorial');

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<string>({
            url: '/api/users/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    getAllUser({ username }: GetAllUserRequest): Observable<Array<User>>
    getAllUser({ username }: GetAllUserRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<User>>>
    getAllUser({ username }: GetAllUserRequest, opts?: OperationOpts): Observable<Array<User> | AjaxResponse<Array<User>>> {

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        const query: HttpQuery = {};

        if (username != null) { query['username'] = username; }

        return this.request<Array<User>>({
            url: '/api/users',
            method: 'GET',
            headers,
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    getUserById({ id }: GetUserByIdRequest): Observable<User>
    getUserById({ id }: GetUserByIdRequest, opts?: OperationOpts): Observable<AjaxResponse<User>>
    getUserById({ id }: GetUserByIdRequest, opts?: OperationOpts): Observable<User | AjaxResponse<User>> {
        throwIfNullOrUndefined(id, 'id', 'getUserById');

        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<User>({
            url: '/api/users/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

    /**
     */
    updateUser({ id, user }: UpdateUserRequest): Observable<User>
    updateUser({ id, user }: UpdateUserRequest, opts?: OperationOpts): Observable<AjaxResponse<User>>
    updateUser({ id, user }: UpdateUserRequest, opts?: OperationOpts): Observable<User | AjaxResponse<User>> {
        throwIfNullOrUndefined(id, 'id', 'updateUser');
        throwIfNullOrUndefined(user, 'user', 'updateUser');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'Authorization': this.configuration.apiKey('Authorization') }), // Authorization authentication
        };

        return this.request<User>({
            url: '/api/users/{id}'.replace('{id}', encodeURI(id)),
            method: 'PUT',
            headers,
            body: user,
        }, opts?.responseOpts);
    };

}
