// tslint:disable
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    PostRequest,
} from './';

/**
 * @export
 * @interface AddPostOnCurrentUserRequest
 */
export interface AddPostOnCurrentUserRequest {
    /**
     * @type {Blob}
     * @memberof AddPostOnCurrentUserRequest
     */
    file?: Blob;
    /**
     * @type {PostRequest}
     * @memberof AddPostOnCurrentUserRequest
     */
    post: PostRequest;
}
