// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ComExampleSpringDemoLoginRefreshtokenErrorMessage
 */
export interface ComExampleSpringDemoLoginRefreshtokenErrorMessage {
    /**
     * @type {number}
     * @memberof ComExampleSpringDemoLoginRefreshtokenErrorMessage
     */
    value?: number;
    /**
     * @type {string}
     * @memberof ComExampleSpringDemoLoginRefreshtokenErrorMessage
     */
    date?: string;
    /**
     * @type {string}
     * @memberof ComExampleSpringDemoLoginRefreshtokenErrorMessage
     */
    message?: string;
    /**
     * @type {string}
     * @memberof ComExampleSpringDemoLoginRefreshtokenErrorMessage
     */
    description?: string;
}
