// tslint:disable
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * @type {number}
     * @memberof Comment
     */
    id?: number;
    /**
     * @type {string}
     * @memberof Comment
     */
    message?: string;
    /**
     * @type {string}
     * @memberof Comment
     */
    createDateTime?: string;
    /**
     * @type {string}
     * @memberof Comment
     */
    updateDateTime?: string;
}
