// tslint:disable
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Comment,
    FileInfo,
    User,
} from './';

/**
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * @type {number}
     * @memberof Post
     */
    id?: number;
    /**
     * @type {string}
     * @memberof Post
     */
    description?: string;
    /**
     * @type {number}
     * @memberof Post
     */
    likeCount?: number;
    /**
     * @type {User}
     * @memberof Post
     */
    user?: User;
    /**
     * @type {Array<Comment>}
     * @memberof Post
     */
    comments?: Array<Comment>;
    /**
     * @type {FileInfo}
     * @memberof Post
     */
    fileInfo?: FileInfo;
    /**
     * @type {string}
     * @memberof Post
     */
    createDateTime?: string;
    /**
     * @type {string}
     * @memberof Post
     */
    updateDateTime?: string;
}
