// tslint:disable
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * @type {number}
     * @memberof Role
     */
    id?: number;
    /**
     * @type {string}
     * @memberof Role
     */
    name?: RoleNameEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum RoleNameEnum {
    User = 'ROLE_USER',
    Moderator = 'ROLE_MODERATOR',
    Admin = 'ROLE_ADMIN'
}

